/*

### ⚔️ Blind Story-Stripping Challenge 24: The Neon Grid Crisis

**Problem Statement:**

You have been appointed as the Chief Architect of the Neon Grid, a sprawling cyberpunk metropolis divided into `N` contiguous sectors. Each sector is powered by a massive Quantum Core. The current power output of these cores is represented by an array `P`, where `P[i]` denotes the terawatts of power generated by the core in the `i-th` sector.

The Grid is highly unstable. To prevent catastrophic cascading blackouts, the central AI mainframe frequently runs diagnostic sweeps. When the AI initiates a sweep on a continuous block of sectors from sector `L` to sector `R`, its primary objective is to pinpoint the sector with the absolute lowest power output within that range so it can redirect emergency shielding to that specific vulnerability.

Simultaneously, your elite teams of field engineers are running across the grid, constantly repairing and upgrading cores in real-time. An engineer might rip out the old Quantum Core in a specific sector and install a new one, instantly altering that sector's power output to a completely new value.

You are handed a log of `Q` events that occurred during a massive neon storm. Each event is either a field engineer's intervention or an AI diagnostic request.

* **Event Type 1:** `1 idx V` — A field engineer replaces the core at sector `idx`, updating its power output to exactly `V` terawatts.
* **Event Type 2:** `2 L R` — The AI runs a diagnostic sweep from sector `L` to sector `R` (inclusive) and needs to know the minimum power output in that range.

Your task is to write a system that processes these events and outputs the result of every AI diagnostic sweep in sequential order.

**Constraints:**
* 1 <= N <= 10^5
* 1 <= Q <= 10^5
* 1 <= P[i] <= 10^9
* 0 <= idx < N
* 1 <= V <= 10^9
* 0 <= L <= R < N
* 0-based indexing is used for all sectors.

**INPUT FORMAT:**
Line 1: An integer `N`, denoting the number of sectors.
Line 2: `N` space-separated integers, representing the initial power array `P`.
Line 3: An integer `Q`, denoting the number of events.
Next `Q` lines: Three space-separated integers representing the event type and its parameters (`1 idx V` or `2 L R`).

**Sample Input:**

6
15 8 20 5 12 25
5
2 1 4
1 3 30
2 1 4
1 1 2
2 0 2


**Sample Output:**

5
8
2


***

*/

#include<iostream>
#include<vector>

using namespace std;

class SegmentTree{
  vector<int>arr;
  vector<int>tree;
  int n;

  void build_segment_tree(int node,int start,int end){
    if(start == end){
      tree[node] = arr[start];
      return;
    }

    int mid = start + (end - start)/2;
    int left_child = 2 * node + 1;
    int right_child = 2 * node + 2;

    build_segment_tree(left_child,start,mid);
    build_segment_tree(right_child,mid+1,end);

    tree[node] = min(tree[left_child], tree[right_child]); // HERE

  }

  void update_segment_tree(int node,int start,int end,int index, int value){
    if(start == end){
      arr[index] = value;
      tree[node] = value;
      return;
    }

    int mid = start + (end - start) / 2;
    int left_child = 2 * node + 1;
    int right_child = 2 * node + 2;


    if(index <= mid){
      update_segment_tree(left_child, start, mid, index,value);
    }else{
      update_segment_tree(right_child, mid + 1, end, index, value);
    }
    
    tree[node] = min(tree[left_child], tree[right_child]); // HERE
  }

  int query_segment_tree(int node,int start,int end, int L,int R){
    // Case 1: Completely OUTSIDE
    if(start > R || end < L){
      return 1e9;
    }
    // Case 2: Completely INSIDE
    if(start >=L && end <= R){
      return tree[node];
    }

    // Case 3: Partially OUTSIDE
    int mid = start + (end - start) / 2;
    int left_child = 2 * node + 1;
    int right_child = 2 * node + 2;

    int left_ans = query_segment_tree(left_child,start,mid,L,R);
    int right_ans = query_segment_tree(right_child,mid+1,end,L,R);

    return min(left_ans,right_ans);

  }

  public:
  SegmentTree(vector<int>&input_arr){
    n = input_arr.size();
    arr = input_arr;
    tree.resize(4*n,1e9);
    build_segment_tree(0,0,n-1);
  }

  void update(int index,int value){
    update_segment_tree(0,0,n-1,index,value);
  }

  int query(int L,int R){
    return query_segment_tree(0,0,n-1,L,R);
  }
};

class Solution{
  public:
  void solution(){
    vector<int> arr = {15, 8 ,20, 5, 12, 25};
    vector<vector<int>> queries = {{2, 1, 4}, {1, 3, 30}, {2, 1, 4}, {1, 1, 2}, {2 ,0, 2}};
    SegmentTree st = SegmentTree(arr);

    for(auto &query:queries){
      int type = query[0];
      if(type == 1){
        // UPDATE
        int index = query[1],value = query[2];
        st.update(index,value);
      }else{
        // Query
        int L = query[1], R = query[2];
        cout<<st.query(L,R)<<"\n";
      }
    }
  }
};

int main(){
  cout<<"\n";
  Solution sol = Solution();
  sol.solution();
  cout<<"\n";
}